"""create tables: places, reviews, place_links

Revision ID: c4de2c003740
Revises: dd344f2a8e49
Create Date: 2025-10-18 16:43:15.355577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c4de2c003740"
down_revision: Union[str, None] = "dd344f2a8e49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "places",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=True),
        sa.Column("name_norm", sa.String(length=512), nullable=False),
        sa.Column("address", sa.String(length=1024), nullable=True),
        sa.Column("address_norm", sa.String(length=1024), nullable=False),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(rating IS NULL) OR (rating >= 0 AND rating <= 5)",
            name="ck_places_rating_range",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_places_source_external"),
    )
    op.create_index("ix_places_address_norm", "places", ["address_norm"], unique=False)
    op.create_index(
        "ix_places_name_norm_city", "places", ["name_norm", "city"], unique=False
    )
    op.create_table(
        "place_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("place_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["place_id"], ["places.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source", "external_id", name="uq_place_links_source_external"
        ),
    )
    op.create_index(
        "ix_place_links_place_id", "place_links", ["place_id"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("place_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("text", sa.String(length=8000), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.CheckConstraint(
            "(rating IS NULL) OR (rating >= 0 AND rating <= 5)",
            name="ck_reviews_rating_range",
        ),
        sa.ForeignKeyConstraint(["place_id"], ["places.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_reviews_source_external"),
    )
    op.create_index("ix_reviews_place_id", "reviews", ["place_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reviews_place_id", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_place_links_place_id", table_name="place_links")
    op.drop_table("place_links")
    op.drop_index("ix_places_name_norm_city", table_name="places")
    op.drop_index("ix_places_address_norm", table_name="places")
    op.drop_table("places")
    # ### end Alembic commands ###
