"""add is_admin

Revision ID: 19334ef1a6a2
Revises: 080816f7668e
Create Date: 2025-11-24 15:23:53.534211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "19334ef1a6a2"
down_revision: Union[str, None] = "080816f7668e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    op.create_table(
        "places",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("source", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "external_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column(
            "name_norm", sa.VARCHAR(length=512), autoincrement=False, nullable=False
        ),
        sa.Column(
            "address", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
        sa.Column(
            "address_norm", sa.VARCHAR(length=1024), autoincrement=False, nullable=False
        ),
        sa.Column("city", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.Column("url", sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
        sa.Column("phone", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column(
            "rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "raw_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.CheckConstraint(
            "rating IS NULL OR rating >= 0::double precision AND rating <= 5::double precision",
            name="ck_places_rating_range",
        ),
        sa.PrimaryKeyConstraint("id", name="places_pkey"),
        sa.UniqueConstraint("source", "external_id", name="uq_places_source_external"),
    )
    # ### end Alembic commands ###
