"""add bookings

Revision ID: 080816f7668e
Revises: c4de2c003740
Create Date: 2025-11-17 14:39:32.677512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "080816f7668e"
down_revision: Union[str, None] = "c4de2c003740"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reviews_place_id", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_places_address_norm", table_name="places")
    op.drop_index("ix_places_name_norm_city", table_name="places")
    op.drop_index("ix_place_links_place_id", table_name="place_links")
    op.drop_table("place_links")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place_links",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("place_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("source", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "external_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name="place_links_place_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="place_links_pkey"),
        sa.UniqueConstraint(
            "source", "external_id", name="uq_place_links_source_external"
        ),
    )
    op.create_index(
        "ix_place_links_place_id", "place_links", ["place_id"], unique=False
    )
    op.create_table(
        "places",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('places_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("source", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "external_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column(
            "name_norm", sa.VARCHAR(length=512), autoincrement=False, nullable=False
        ),
        sa.Column(
            "address", sa.VARCHAR(length=1024), autoincrement=False, nullable=True
        ),
        sa.Column(
            "address_norm", sa.VARCHAR(length=1024), autoincrement=False, nullable=False
        ),
        sa.Column("city", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.Column("url", sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
        sa.Column("phone", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column(
            "rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "raw_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.CheckConstraint(
            "rating IS NULL OR rating >= 0::double precision AND rating <= 5::double precision",
            name="ck_places_rating_range",
        ),
        sa.PrimaryKeyConstraint("id", name="places_pkey"),
        sa.UniqueConstraint("source", "external_id", name="uq_places_source_external"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_places_name_norm_city", "places", ["name_norm", "city"], unique=False
    )
    op.create_index("ix_places_address_norm", "places", ["address_norm"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("place_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("source", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.Column(
            "external_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("author", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("text", sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
        sa.Column(
            "published_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "raw_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "rating IS NULL OR rating >= 0::double precision AND rating <= 5::double precision",
            name="ck_reviews_rating_range",
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["places.id"],
            name="reviews_place_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="reviews_pkey"),
        sa.UniqueConstraint("source", "external_id", name="uq_reviews_source_external"),
    )
    op.create_index("ix_reviews_place_id", "reviews", ["place_id"], unique=False)
    # ### end Alembic commands ###
